Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
AllowedHosts: "*"
Settings:
  IpWhite: "*"
  LocalPublicKey: |
    -----BEGIN PUBLIC KEY-----
    -----END PUBLIC KEY-----
  LocalPrivateKey: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
  RemotePublicKey: |
    -----BEGIN PUBLIC KEY-----
    -----END PUBLIC KEY-----