name: shashlik-nuget

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        #with:
        #  dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore ./Component.Package.sln
      - name: Build
        run: dotnet build ./Component.Package.sln --configuration Release --no-restore
      - name: Pack
        run: dotnet pack ./Component.Package.sln --include-source --configuration Release --no-restore --output ./nugetPackages
      - name: Publish
        run: dotnet nuget push --skip-duplicate "./nugetPackages/*.symbols.nupkg" -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json